# Generated by Django 4.2 on 2023-05-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, verbose_name='브랜드명')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='업종명')),
            ],
        ),
        migrations.CreateModel(
            name='Jumpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumpo_name', models.CharField(max_length=50, verbose_name='점포명')),
                ('street_address', models.CharField(max_length=200, verbose_name='도로명주소')),
                ('latitude', models.FloatField(blank=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, verbose_name='경도')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jumpo',
            constraint=models.UniqueConstraint(fields=('jumpo_name', 'street_address'), name='jumpo_address'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
