# Generated by Django 4.2 on 2023-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_jumpo_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpo',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='jumpo',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='경도'),
        ),
    ]
